pyusb/pyusb

- usb/backend/libusb1.py
- usb/core.py
- usb/util.py
In some cases, we need to get the usb device speed type to attach
it to specific usb controller. Fortunately, it's easy to get usb
device speed information with libusb1.0.
> Support for getting usb device speed

- usb/util.py
This removes the DeprecationWarning that warns that tostring() is obsolete when running with Python 3.2+
> util: change tostring() to tobytes() when running with Python 3.2+

- usb/core.py
wIndex is the interface number to be claimed only for
standard request types. For example Silicon Labs cp2103 defines
a vendor control transfer to set some GPIO pins though wIndex
parameter (se AN571 page 17).
> Claim interface only for standard control transfer requests.

- usb/backend/libusb0.py
Solaris ships with a libusb0 implementation (that works both with usb devices attached to the host, and those attached to SunRay thin clients served by the host!). But the libusb0 backend wasn't working right because the wrong value was being obtained for PC_PATH_MAX. Fixed here.
One problem remains: the library on Solaris is found at /usr/sfw/lib/libusb.so.1 which is not found automatically by the backend. I am not sure what would be your preferred way to fix that. Just add to the list of names in _load_library? Define a different _load_library if sys.platform is sunos5? Something else?
For right now, the client code in my application is calling get_backend directly to handle this problem, but it will be nice to take that out once the backend can find the library without help.
> Support the libusb0 that ships in Solaris

- usb/_interop.py
- usb/legacy.py
README.rst was saying 2.4+ should be supported but some vestiges from 2.3
were in _interop.py.
http://sourceforge.net/p/pyusb/mailman/message/34078264/
> Conform _interop to the README goal to support 2.4+.

- usb/core.py
- usb/util.py
This started off just as an exercise in not having the serial number come back as Љ if the device doesn't have one, and grew into a little more work to expose the device's available language IDs as a property on Device.
> Handling device strings; making device's LANGID list accessible.

- setup.py
These are the ones I came up with by reading down the PyPi trove classifier list while thinking "who would be using a usb library for what?". For the operating systems, I looked around for what was said to support any of the backend libraries, and for Python implementations I relied on a paper naming several that either did or intended to (in 2006) support ctypes.
I thought about a bunch of the multimedia classifiers (sound and video capture, MIDI, etc.) as a lot of that stuff is usb, but decided to leave them out because those classifier might be more appropriate for specific  code working on top of pyusb.
> For discussion anyway, one attempt at some relevant trove classifiers.

- usb/backend/libusb1.py
This works for me. Tested on Ubuntu 10.04 (Lucid) with libusb-1.0-0 package version 2:1.0.6-1
> fix get_device_speed for old libusb versions

- docs/tutorial.rst
Clarify the different methods of setting the configuration.
> doc: tutorial fix typo in cfg setting

- docs/tutorial.rst
The link for OpenUSB doesn't work. It says "Page not found" on sourceforge. I replaced it with the link to the OpenUSB sourceforge wiki
> Fix OpenUSB link

- usb/core.py
This matches what the Linux kernel does in `check_intf()` when called from `check_ctrlrecip()`
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/usb/core/devio.c
and thus helps to prevent annoying warnings from the kernel.
The previous code did this for `STANDARD` type transfers already, but not for `CLASS`.
> ctrl_transfer: claim receiving interface for non-VENDOR transfers

- usb/_interop.py
- usb/core.py
- usb/util.py
all( iter_ ) is more explicit than reduce( lambda x, y:x and y, iter_, True ),
especially since reduce is no longer a builtin.  Use all instead of
complicated multi-line reduce statement for easier code comprehension.
Also, introduce _all interop since all was introduced in 2.5
> make find and find_descriptor easier to understand

- usb/backend/libusb0.py
- usb/backend/libusb1.py
- usb/backend/openusb.py
- usb/libloader.py
I actually realize you might want to keep this typo to prevent a breaking change, but it's an easy fix I thought I'd offer.
> Typo fix: replace LibaryException with LibraryException.

- usb/libloader.py
The documentation of cygwin_cls and others_cls got mixed up.
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>
> usb/libloader.py: load_locate_library parameter documentation

- usb/legacy.py
Properly implement legacy compatibility for the following fields which
were previously set to default values:
Bus.location = 0
Device.devnum = None
> legacy: set Bus.location and Device.devnum

- .gitignore
And any other .egg-info directories that might be added by setuptools.
> .gitignore pyusb.egg-info

- LICENSE
- setup.py
- tests/devinfo.py
- tests/test_backend.py
- tests/test_control.py
- tests/test_find.py
- tests/test_integration.py
- tests/test_legacy.py
- tests/test_util.py
- tests/testall.py
- tests/utils.py
- usb/__init__.py
- usb/_debug.py
- usb/_interop.py
- usb/_lookup.py
- usb/_objfinalizer.py
- usb/backend/__init__.py
- usb/backend/libusb0.py
- usb/backend/libusb1.py
- usb/backend/openusb.py
- usb/control.py
- usb/core.py
- usb/legacy.py
- usb/libloader.py
- usb/util.py
The current license is a custom license, based on BSD. Apache 2.0 is well understood and BSD compatible. Moving PyUSB to a standard license helps companies adopt usage as it's well understood.
> Moving to the standard Apache 2.0 License.

- docs/faq.rst
Unlike the example used to suggest, `get_active_configuration` raises `USBError('Configuration not set')` if there's no active configuration set yet.
> Fix example for when there's no active configuration

- usb/backend/libusb1.py
In Python, two adjacent strings get concatenated implicitely.
Missing commas in multi-line string lists is a common source of bugs
causing unwanted string concatenation. In this case, it is clear that this
comma is missing by mistake and there should not be a concatenation.
I also add a comma on the last item for consistency.
> Add missing comma in string list

- usb/backend/libusb1.py
Fix incorrectly exposed constant `LIBUSB_SUCESS` in `libusb1.py` backend.
> Typo fix: libusb1.py LIBUSB_SUCESS -> LIBUSB_SUCCESS

- usb/backend/libusb1.py
I think the cause of #203 is each time libusb1.get_backend() is being called, a new _LibUSB backend object is being created and returned. 
When the first of these goes out of scope and is finalized, it de-inits the underlying libusb1 library, invalidating any remaining backend object instances and calls made through them.
My fix is to assume that there is only going to be one _LibUSB backend object and cache it, returning it to subsequent libusb1.get_backend calls. This assumption mirrors the one made about _lib.
> Fix #203: libusb sometimes cleaned up too early.

- usb/backend/libusb1.py
If `libusb_init` throws an exception, then `ctx` is null here
> Don't call libusb_exit on a null pointer

- .github/workflows/run_tox.yml
- tox.ini
This PR adds a github action workflow to run the tests for python 2.7, 3.5, 3.6, 3.7, 3.8 on windows, linux and macos via tox.
Currently windows-py27 fails due to an ImportError (fix: https://github.com/ap--/pyusb/commit/5ece7fa23597d99abcb62df413ef9d22fcbf3f0d) and all windows tests throw warnings because no backend can be imported.
Since tox runs `python setup.py sdist` to install the package in the test environment, this could be used to verify that `setuptools_scm`'s version is correctly included.
Cheers :smiley: 
Andreas
> run tests via tox and github actions

- .gitignore
- pyproject.toml
- setup.cfg
- setup.py
- usb/__init__.py
Automatically generates the `usb.__version__` string on installation.
Would close pyusb/pyusb#298.
**This PR adds `setuptools_scm` to automatically generate version strings on install.**
There's still a few things to be considered before this should be merged:
- what are the target python versions and OSes? (Let's create a list here and I can work my way through all of them to see if packaging won't fail due to old setuptools versions)
- I set the setuptools_scm `version_scheme` to **post-release** which generates version strings like `1.0.2.post42+SHORTGITHASH` (42 commits after tag '1.0.2') instead of the default which would increase the micro version and create `1.0.3.dev42+SHORTGITHASH`, but that's just personal preference I guess. (see …
> Use setuptools_scm for versioning

- setup.py
This PR adds "-editable" to `usb.__version__` of pyusb installs done via `python setup.py develop` or `pip install -e .`
Cheers,
Andreas :smiley:
> Indicate editable installs in version string

- setup.cfg
- tests/test_backend.py
- tests/test_control.py
- tests/test_integration.py
- tests/test_legacy.py
This PR allows running the testsuite with pytest without errors. It's a fix for #319 
<br>
With the current unittest testsuite, only 7 tests are run that do not require the hardware test device referenced in tests/devinfo.py `(ID_VENDOR = 0x04d8, ID_PRODUCT = 0xfa2e)`. When pytest is run, it autodiscovers all `unittest.TestCase` subclasses and tries to run them. This has issues because the TestCase subclasses do not use setup and teardown consistently and have some non-independent test. So for implementing support for pytest, there's basically three options to consider:
This is the easiest option, and it's implemented in this PR. It simply ignores the TestCases that require the test hardware, and so when you run pytest in the project root folder, the 7 tests that do not rely on the device …
> tests: minimal changeset for pytest support

- usb/backend/__init__.py
There is a small typo in usb/backend/__init__.py.
Should read `respectively` rather than `respectivelly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, respectivelly -> respectively

- usb/core.py
Otherwise the type check for claim_interface will fail and the
error message is less helpful.
Signed-off-by: Tormod Volden <debian.tormod@gmail.com>
BEFORE:
```
>>> dev.set_interface_altsetting(0, 1)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "pyusb/usb/core.py", line 936, in set_interface_altsetting
self._ctx.managed_set_interface(self, interface, alternate_setting)
File "pyusb/usb/core.py", line 113, in wrapper
return f(self, *args, **kwargs)
File "pyusb/usb/core.py", line 210, in managed_set_interface
self.managed_claim_interface(device, i)
File "pyusb/usb/core.py", line 113, in wrapper
return f(self, *args, **kwargs)
File "pyusb/usb/core.py", line 178, in managed_claim_interface
self.backend.claim_interface(self.handle, i)
File …
```
> set_interface: Raise ValueError if no match is found

- setup.py
Related to #363 
This PR probably stops further releasing (> v1.1.1) to Python 2.
I just copied https://github.com/chainer/chainer/pull/8517 and am not sure if this really works.
Please check carefully.
> Stop further releasing to Python 2

- usb/core.py
Commit 251dbc15df00b5 (core: implement `Device.__eq__`") had the side effect of making `Device` objects unhashable, so they could no longer be included in a `set()`.  This was a regression from v1.1.1.  Add a corresponding `__hash__()` method so that Device objects are hashable again.
Fixes eblot/pyftdi#256
> Make Device hashable again

- setup.cfg
Fix the following warning:
/usr/lib/python3.10/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
> Fix the setuptools underscore warning

- usb/core.py
As per the 'FIXME' comment, the current value uses a different multiplier for USB 3 (ie superspeed) devices.
This change uses the USB version from bcdUSB to determine the correct multiplier.
> Fix bMaxPower conversion for USB 3 devices

- usb/legacy.py
Introduced in https://github.com/pyusb/pyusb/commit/e658484a03af0e8b3733105c67fe23d76232fc03. I believe this is a typo.
`hasattr(self, 'self.dev')` will never evaluate to `True` so `_finalize_object` will never actually run.
> legacy: Fix `DeviceHandle` finalizer checking for the wrong attribute

- .github/workflows/run_tox.yml
- README.rst
- docs/tutorial.rst
- setup.py
- tox.ini
- usb/_interop.py
- usb/libloader.py
On Apple Silicon, homebrew will by default (and, really, it's the only recommended way to use it) use the `/opt/homebrew` prefix. The old `/usr/local` prefix is retained for the use of Intel/x86_64 homebrew.
This means that libraries (e.g. LibUSB) installed through homebrew on Apple Silicon will end up in `/opt/homebrew/lib/`. But that location isn't one of the search paths checked by `ctypes.util.find_library` (which is what we use if no custom `find_library` is supplied by the caller). Homebrew [patches](https://github.com/Homebrew/homebrew-core/blob/e91fb0c6e50a/Formula/p/python%403.11.rb#L196-L203) the Python interpreters they distribute, but other/stock interpreters don't know about this additional location for libraries.
As this is a frequent enough issue, let's check for that …
> Search in default homebrew prefix on Apple Silicon

- usb/libloader.py
I have a project that is based on python-ecspos which depends on Pyusb. This project is built as a Snap which is then deployed onto an Ubuntu Core based system to communicate with a USB based receipt printer.
Libusb access is granted to a snap by specifying it as a stage-package in the ```snapcraft.yaml``` file per below example.
```
stage-packages:
- libusb-1.0-0
```
Libusb is then accessible via the path of ```$snap/usr/lib/{architecture}/libusb-1.0-0.so.0```. ```find_library``` currently does not find the backend and fails to access any USB device.
This patch adds a check if the PyUSB  is running as a SNAP, and if so, attempts to load the library from the $SNAP location.
This patch only caters to ```x86_64-linux-gnu``` architecture, though additional architectures can be added to the …
> Add Additional Library Location for Snapcraft Support
